"""add indexes to join tables

Revision ID: 6a9dea9cd3a8
Revises: 6d319c040b5e
Create Date: 2024-11-12 22:21:15.471059

"""
from alembic import op
import sqlalchemy as _


# revision identifiers, used by Alembic.
revision = '6a9dea9cd3a8'
down_revision = '6d319c040b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes_join', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_join_song_id'), ['song_id'], unique=False)

    with op.batch_alter_table('playlists_join', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlists_join_song_id'), ['song_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists_join', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_join_song_id'))

    with op.batch_alter_table('likes_join', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_join_song_id'))

    # ### end Alembic commands ###
