# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python + uv
      uses: astral-sh/setup-uv@v3
      with:
        python-version: "3.12"
        version: "0.4.11"
        enable-cache: true

    - name: Install dependencies
      working-directory: backend
      run: |
        uv sync
    - name: Run ruff check
      working-directory: backend
      run: |
        uv run ruff check
    - name: Run ruff format
      working-directory: backend
      run: |
        uv run ruff format --check
    - name: Run pyright
      working-directory: backend
      run: |
        uv run pyright
